export const ADD_TO_CART = 'ADD_TO_CART';
export const TOGGLE_CART = 'TOGGLE_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const DECREMENT_PRODUCT_CART_QUANTITY = 'DECREMENT_PRODUCT_CART_QUANTITY';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
